export default {
    YEAR: 'YEAR',
    MONTH: 'MONTH',
    LEFT: 'LEFT',
    RIGHT: 'RIGHT',
	HOUR: 'HOUR',
	MINUTE: 'MINUTE',
    SECOND: 'SECOND',

    YEAR_MODEL: 'YEAR_MODEL',
    YEAR_MONTH_MODEL: 'YEAR_MONTH_MODEL',
	MONTH_MODEL: 'MONTH_MODEL',
	MONTH_DAY_MODEL: 'MONTH_DAY_MODEL',
    ALL_MODEL: 'ALL_MODEL',

	AUTO: 'AUTO',
	UP: 'UP',
	DOWN: 'DOWN',

	START: 'START',
	END: 'END',

	DATE_HOUR: 'DATE_HOUR',
	DATE_HOUR_MINUTE: 'DATE_HOUR_MINUTE',
	DATE_TIME: 'DATE_TIME',
}
